# SPDX-FileCopyrightText: 2025 Tymoteusz Blazejczyk <tymoteusz.blazejczyk@tymonx.com>
# SPDX-License-Identifier: Apache-2.0

name: Cocotb JUnit - Testing CI Reports
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, workflow_dispatch]
jobs:
    test-with-makefile:
        runs-on: ubuntu-latest
        container:
            image: registry.gitlab.com/tymonx/ghdl:latest
            options: --cpus 1
            env:
                COCOTB_PATHS_RELATIVE_TO: ${GITHUB_WORKSPACE}
                HDL_TOPLEVEL_LANG: vhdl
                TOPLEVEL_LANG: ${HDL_TOPLEVEL_LANG}
                WAVES: 1
                SIM: ghdl
                SIM_ARGS: --wave=wave.ghw
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - run: uv venv
            - name: Activate virtual environment
              run: echo PATH=${GITHUB_WORKSPACE}/.venv/bin:$PATH >> $GITHUB_ENV
            - run: uv pip install git+https://github.com/tymonx/cocotb.git@chore/xunit-reporter pytest
            - run: COCOTB_ATTACHMENTS=examples/simple_dff/wave.ghw make -C examples/simple_dff
            - name: Publish Test Report
              uses: mikepenz/action-junit-report@v5
              if: success() || failure() # always run even if the previous step fails
              with:
                  report_paths: '**/results.xml'
